/** Captions for the announcer pack (generated from "Announcer Dialogue.txt") */
export const ANNOUNCER_LINES = {
"alright": "Alright…",
"amazing": "Amazing!",
"anewchallenger": "A new challenger!",
"anewchallengerapproaches": "A new challenger approaches!",
"battle": "Battle!",
"battle2": "Battle!",
"battleisabouttoexplode": "The battle is about to explode!",
"battleofthecentury": "The battle of the century!",
"chain": "Chain!",
"chooseyourcharacter": "Choose your character!",
"combo": "Combo!",
"combobreaker": "Combo breaker!",
"combodouble": "Double combo!",
"combohyper": "Hyper combo!",
"combosuper": "Super combo!",
"combotriple": "Triple combo!",
"comboultra": "Ultra combo!",
"continue": "Continue!",
"continue2": "Continue!",
"countdownfrom10": "10… 9… 8… 7… 6… 5… 4… 3… 2… 1…",
"countdownfrom3-2": "3… 2… 1…",
"countdownfrom3": "3… 2… 1…",
"danger": "Danger!",
"danger2": "Danger!",
"danger3": "Danger!",
"defeat": "Defeat!",
"defeat2": "Defeat!",
"defeated": "Defeated!",
"defeated2": "Defeated!",
"dudecomeon": "Dude, come on!",
"duel": "Duel!",
"engage": "Engage!",
"engage2": "Engage!",
"engarde": "En garde!",
"excellent": "Excellent!",
"excellent2": "Excellent!",
"failure": "Failure!",
"failure2": "Failure!",
"fight": "Fight!",
"fight2": "Fight!",
"fight3": "Fight!",
"finallap": "Final lap!",
"finalmatch": "Final match!",
"finalround": "Final round!",
"finish": "Finish!",
"finished": "Finished!",
"finished2": "Finished!",
"firstblood": "First blood!",
"firstblood2": "First blood!",
"game": "Game!",
"game2": "Game!",
"game3": "Game!",
"gameover": "Game Over!",
"gameover2": "Game Over!",
"getready": "Get ready!",
"getreadyforanewchallenger": "Get ready for a new challenger!",
"getreadyforthenextfight": "Get ready for the next fight!",
"go": "Go!",
"go2": "Go!",
"go3": "Go!",
"godlike": "Godlike!",
"goforbroke": "Go for broke…",
"great": "Great!",
"great2": "Great!",
"herecomesaclown": "Here comes a clown!",
"herecomesanewchallenger": "Here comes a new challenger!",
"itsallontheline": "It’s all on the line…",
"iveneverseenmoves": "I've never seen moves like this!",
"knockout": "Knockout!",
"ko": "K.O.!",
"ko2": "K.O.!",
"ko3": "K.O.!",
"letsrock": "Let’s rock…",
"loser": "Loser!",
"matchcomplete": "Match complete!",
"matchover": "Match over!",
"maythebestfighterwin": "May the best fighter win!",
"mygod": "My god!",
"notbad": "Not bad!",
"overthetop": "Over the top…",
"perfect": "Perfect!",
"perfect2": "Perfect!",
"ready": "Ready!",
"ready2": "Ready!",
"round1-2": "Round 1!",
"round1": "Round 1!",
"round2-2": "Round 2!",
"round2": "Round 2!",
"round3-2": "Round 3!",
"round3": "Round 3!",
"round4-2": "Round 4!",
"round4": "Round 4!",
"round5-2": "Round 5!",
"round5": "Round 5!",
"round6-2": "Round 6!",
"round6": "Round 6!",
"round7-2": "Round 7!",
"round7": "Round 7!",
"roundcomplete": "Round complete!",
"roundover": "Round over!",
"roundset": "Round set!",
"selectyourfighter": "Select your fighter!",
"showtime": "Showtime!",
"sick": "Sick!",
"startyourengines": "Start your engines!",
"strike": "Strike!",
"thatwasadangtechgrab": "That was a dang tech grab!",
"thatwasclose": "That was close!",
"theyreonfire": "They’re on fire!",
"thisistheend": "This is the end…",
"thisistheend2": "This is the end…",
"thisshouldbegood": "This should be good…",
"timesover": "Time's over!",
"timesup": "Time's up!",
"timesup2": "Time's up!",
"triumphordie": "Triumph or die!",
"untouchable": "Untouchable!",
"versus": "Versus!",
"versus2": "Versus!",
"welcome": "Welcome…",
"whowillwin": "Who will win?",
"willyoustayandfight": "Will you stay and fight?",
"winner": "Winner!",
"winner2": "Winner!",
"winner3": "Winner!",
"wow": "Wow!",
"youlose": "You lose!",
"youlose2": "You lose!",
"youreincredible": "You’re incredible!",
"youreinfirstplace": "You’re in first place!",
"yourenotgonnagetup": "You're not even gonna try to get up?",
"yousuck": "You suck!",
"youwin": "You win!",
"youwin2": "You win!"
};
